# Generated by Django 5.1.1 on 2024-12-27 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='system_roles',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SystemRole',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
