# Generated by Django 5.1.1 on 2025-01-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0001_initial'),
        ('AppProduct', '0002_outlet_address_outlet_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='outlet',
            field=models.ManyToManyField(related_name='outlet_users', to='AppProduct.outlet'),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='sys_role_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
