# Generated by Django 5.1.1 on 2024-12-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemrole',
            name='sys_role_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
