# Generated by Django 5.1.1 on 2024-12-18 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='tbl_user_profile',
        ),
    ]
