# Generated by Django 5.1.1 on 2024-12-27 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
