# Generated by Django 5.1.1 on 2024-12-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0004_alter_userprofile_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'tbl_role_permission',
            },
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='sys_role_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='systemrole',
            name='updated_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='systemrole',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', to='AppAccount.permissions'),
        ),
    ]
