# Generated by Django 5.1.1 on 2025-01-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0004_delete_paymentmethod'),
        ('AppProduct', '0002_outlet_address_outlet_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='outlet',
            field=models.ManyToManyField(related_name='outlet_users', to='AppProduct.outlet'),
        ),
    ]
