# Generated by Django 5.1.1 on 2024-12-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0004_delete_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemrole',
            name='sys_role_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
