# Generated by Django 5.1.1 on 2025-01-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0005_alter_systemrole_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemrole',
            name='sys_role_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
