# Generated by Django 5.1.1 on 2024-12-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0005_permissions_alter_systemrole_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemrole',
            name='sys_role_code',
        ),
    ]
