# Generated by Django 5.1.1 on 2025-01-22 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0007_userprofile_created_by_userprofile_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
