# Generated by Django 5.1.1 on 2025-01-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAccount', '0008_alter_userprofile_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
    ]
