# Generated by Django 5.1.1 on 2024-10-09 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCustomer', '0002_rename_province_customer_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerchannel',
            old_name='channel_name',
            new_name='customer_channel',
        ),
        migrations.RenameField(
            model_name='customertype',
            old_name='type',
            new_name='customer_type',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cus_ch_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='cus_type_code',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCustomer.customerchannel', to_field='customer_channel'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCustomer.customertype', to_field='customer_type'),
        ),
    ]
