# Generated by Django 5.1.1 on 2025-01-22 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0002_rename_shopowner_shop_alter_shop_table'),
        ('AppCustomer', '0002_alter_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AddField(
            model_name='customerchannel',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AddField(
            model_name='customertype',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCustomer.customerchannel'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCustomer.customertype'),
        ),
        migrations.AlterField(
            model_name='customerchannel',
            name='customer_channel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customertype',
            name='customer_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customerchannel',
            unique_together={('shop', 'customer_channel')},
        ),
        migrations.AlterUniqueTogether(
            name='customertype',
            unique_together={('shop', 'customer_type')},
        ),
    ]
