# Generated by Django 5.1.1 on 2025-01-24 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCustomer', '0003_customer_shop_customerchannel_shop_customertype_shop_and_more'),
        ('AppProduct', '0010_product_shop_temporaryproduct_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.outlet'),
        ),
    ]
