# Generated by Django 5.1.1 on 2024-10-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCustomer', '0003_rename_channel_name_customerchannel_customer_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
