# Generated by Django 5.1.1 on 2024-12-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppCustomer', '0001_initial'),
        ('AppProduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_code', models.CharField(max_length=100, null=True, unique=True)),
                ('fee_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_additional_fee',
            },
        ),
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.CharField(blank=True, null=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPOS.additionalfee')),
            ],
            options={
                'db_table': 'tbl_transaction_additional_fee',
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_code', models.CharField(max_length=100, null=True, unique=True)),
                ('salesman_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wholesale_commission', models.CharField(blank=True, max_length=100, null=True)),
                ('retail_commission', models.CharField(blank=True, max_length=100, null=True)),
                ('token_commission', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
                ('outlet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.outlet')),
            ],
            options={
                'db_table': 'tbl_salesman',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(max_length=100, null=True, unique=True)),
                ('quantity', models.CharField(blank=True, null=True)),
                ('gross_total', models.CharField(blank=True, null=True)),
                ('per_discount', models.CharField(blank=True, null=True)),
                ('discounted_value', models.CharField(blank=True, null=True)),
                ('items_discount', models.CharField(blank=True, null=True)),
                ('grand_total', models.CharField(blank=True, null=True)),
                ('advanced_payment', models.CharField(blank=True, null=True)),
                ('due_amount', models.CharField(blank=True, null=True)),
                ('additional_fees', models.CharField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
                ('additional_fee', models.ManyToManyField(through='AppPOS.FeeRecord', to='AppPOS.additionalfee')),
                ('cust_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCustomer.customer', to_field='cust_code')),
                ('outlet_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.outlet')),
                ('salesman_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPOS.salesman', to_field='salesman_code')),
            ],
            options={
                'db_table': 'tbl_transaction',
            },
        ),
        migrations.AddField(
            model_name='feerecord',
            name='transaction_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPOS.transaction'),
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, null=True)),
                ('invoice_item_code', models.CharField(max_length=100, null=True, unique=True)),
                ('quantity', models.CharField(blank=True, null=True)),
                ('rate', models.CharField(blank=True, null=True)),
                ('gross_total', models.CharField(blank=True, null=True)),
                ('per_discount', models.CharField(blank=True, null=True)),
                ('discounted_value', models.CharField(blank=True, null=True)),
                ('item_total', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('invoice_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPOS.transaction', to_field='invoice_code')),
            ],
            options={
                'db_table': 'tbl_transaction_item',
            },
        ),
        migrations.CreateModel(
            name='TransactionReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('total_amount', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('invoice_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPOS.transaction', to_field='invoice_code')),
            ],
            options={
                'db_table': 'tbl_transaction_return',
            },
        ),
    ]
