# Generated by Django 5.1.1 on 2024-10-31 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCustomer', '0005_systemrole'),
        ('AppPOS', '0001_initial'),
        ('AppProduct', '0030_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='invoice_code',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceitem',
            name='sku',
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.CharField(max_length=100, null=True, unique=True)),
                ('quantity', models.CharField(blank=True, null=True)),
                ('gross_total', models.CharField(blank=True, null=True)),
                ('per_discount', models.CharField(blank=True, null=True)),
                ('discounted_value', models.CharField(blank=True, null=True)),
                ('grand_total', models.CharField(blank=True, null=True)),
                ('advanced_payment', models.CharField(blank=True, null=True)),
                ('due_amount', models.CharField(blank=True, null=True)),
                ('additional_fees', models.CharField(blank=True, null=True)),
                ('purchase_date', models.CharField(blank=True, null=True)),
                ('payment_type', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
                ('cust_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCustomer.customer', to_field='cust_code')),
            ],
            options={
                'db_table': 'tbl_transaction',
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_item_code', models.CharField(max_length=100, null=True, unique=True)),
                ('quantity', models.CharField(blank=True, null=True)),
                ('rate', models.CharField(blank=True, null=True)),
                ('gross_total', models.CharField(blank=True, null=True)),
                ('per_discount', models.CharField(blank=True, null=True)),
                ('discounted_value', models.CharField(blank=True, null=True)),
                ('item_total', models.CharField(blank=True, null=True)),
                ('status', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('invoice_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPOS.transaction', to_field='invoice_code')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.product', to_field='sku')),
            ],
            options={
                'db_table': 'tbl_transaction_item',
            },
        ),
        migrations.DeleteModel(
            name='PurchaseInvoice',
        ),
        migrations.DeleteModel(
            name='PurchaseInvoiceItem',
        ),
    ]
