# Generated by Django 5.1.1 on 2024-12-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0001_initial'),
        ('AppProduct', '0012_alter_product_season_alter_temporaryproduct_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='outlet_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.outlet'),
        ),
    ]
