# Generated by Django 5.1.1 on 2024-11-04 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.CharField(blank=True, null=True)),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPOS.additionalfee')),
                ('transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPOS.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='additional_fee',
            field=models.ManyToManyField(through='AppPOS.FeeRecord', to='AppPOS.additionalfee'),
        ),
    ]
