# Generated by Django 5.1.1 on 2025-01-13 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_name', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_payment_method',
            },
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_type',
            new_name='total_pay',
        ),
        migrations.RemoveField(
            model_name='salesman',
            name='outlet',
        ),
        migrations.CreateModel(
            name='TransactionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPOS.paymentmethod')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPOS.transaction')),
            ],
            options={
                'db_table': 'tbl_transaction_payment',
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment',
            field=models.ManyToManyField(through='AppPOS.TransactionPayment', to='AppPOS.paymentmethod'),
        ),
    ]
