# Generated by Django 5.1.1 on 2024-11-04 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0002_feerecord_transaction_additional_fee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feerecord',
            table='tbl_transaction_fee',
        ),
    ]
