# Generated by Django 5.1.1 on 2024-12-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0002_alter_transaction_outlet_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionreturn',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionreturn',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactionreturn',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
