# Generated by Django 5.1.1 on 2025-01-13 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0002_paymentmethod_and_more'),
        ('AppProduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanOutlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProduct.outlet')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppPOS.salesman')),
            ],
            options={
                'db_table': 'tbl_salesman_outlet',
            },
        ),
        migrations.AddField(
            model_name='salesman',
            name='outlet',
            field=models.ManyToManyField(through='AppPOS.SalesmanOutlet', to='AppProduct.outlet'),
        ),
    ]
