# Generated by Django 5.1.1 on 2024-10-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0002_remove_purchaseinvoiceitem_invoice_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='sku',
            field=models.CharField(blank=True, null=True),
        ),
    ]
