# Generated by Django 5.1.1 on 2024-12-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0003_transactionpayment_transaction_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='payment_type',
            new_name='total_pay',
        ),
    ]
