# Generated by Django 5.1.1 on 2025-01-21 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0002_rename_shopowner_shop_alter_shop_table'),
        ('AppPOS', '0003_salesmanoutlet_salesman_outlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='pm_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('shop', 'pm_name')},
        ),
    ]
