# Generated by Django 5.1.1 on 2024-11-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0004_alter_feerecord_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesman_code', models.CharField(max_length=100, null=True, unique=True)),
                ('salesman_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wholesale_commission', models.CharField(blank=True, max_length=100, null=True)),
                ('retail_commission', models.CharField(blank=True, max_length=100, null=True)),
                ('token_commission', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_salesman',
            },
        ),
    ]
