# Generated by Django 5.1.1 on 2025-01-22 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0002_rename_shopowner_shop_alter_shop_table'),
        ('AppPOS', '0004_paymentmethod_shop_alter_paymentmethod_pm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalfee',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AlterField(
            model_name='additionalfee',
            name='fee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='additionalfee',
            unique_together={('shop', 'fee_name')},
        ),
        migrations.AlterUniqueTogether(
            name='salesman',
            unique_together={('shop', 'salesman_name')},
        ),
    ]
