# Generated by Django 5.1.1 on 2024-12-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0004_remove_salesman_outlet_code_salesman_outlet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='grand_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
