# Generated by Django 5.1.1 on 2024-12-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0004_rename_payment_type_transaction_total_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='grand_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
