# Generated by Django 5.1.1 on 2024-11-11 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0005_salesman'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, null=True)),
                ('rate', models.CharField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, null=True)),
                ('total_amount', models.CharField(blank=True, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('invoice_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPOS.transaction', to_field='invoice_code')),
            ],
            options={
                'db_table': 'tbl_transaction_return',
            },
        ),
    ]
