# Generated by Django 5.1.1 on 2025-01-24 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0002_rename_shopowner_shop_alter_shop_table'),
        ('AppPOS', '0005_additionalfee_shop_salesman_shop_and_more'),
        ('AppProduct', '0010_product_shop_temporaryproduct_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='outlet_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.outlet'),
        ),
    ]
