# Generated by Django 5.1.1 on 2024-11-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0006_transactionreturn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionreturn',
            old_name='product',
            new_name='sku',
        ),
    ]
