# Generated by Django 5.1.1 on 2024-11-13 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0007_rename_product_transactionreturn_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='salesman_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppPOS.salesman', to_field='salesman_code'),
        ),
    ]
