# Generated by Django 5.1.1 on 2025-01-24 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0002_rename_shopowner_shop_alter_shop_table'),
        ('AppPOS', '0007_transactionitem_outlet_code_transactionitem_shop'),
        ('AppProduct', '0010_product_shop_temporaryproduct_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionreturn',
            name='outlet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.outlet'),
        ),
        migrations.AddField(
            model_name='transactionreturn',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
    ]
