# Generated by Django 5.1.1 on 2024-11-15 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPOS', '0008_transaction_salesman_code'),
        ('AppProduct', '0030_alter_product_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesman',
            name='outlet_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.outlet', to_field='outlet_code'),
        ),
    ]
