# Generated by Django 5.1.1 on 2024-11-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='attribute_type',
        ),
    ]
