# Generated by Django 5.1.1 on 2025-01-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='contact_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='outlet',
            name='outlet_mobile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
