# Generated by Django 5.1.1 on 2024-11-21 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0002_remove_category_attribute_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatrgoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProduct.attribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppProduct.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='attribute_group',
            field=models.ManyToManyField(through='AppProduct.CatrgoryAttribute', to='AppProduct.attribute'),
        ),
    ]
