# Generated by Django 5.1.1 on 2024-11-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0003_catrgoryattribute_category_attribute_group'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='catrgoryattribute',
            table='tbl_category_attribute',
        ),
    ]
