# Generated by Django 5.1.1 on 2024-11-22 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0004_alter_catrgoryattribute_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.category'),
        ),
        migrations.AddField(
            model_name='temporaryproduct',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='outlet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.outlet'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sub_category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.subcategory'),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.brand'),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='outlet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.outlet'),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='sub_category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.subcategory'),
        ),
    ]
