# Generated by Django 5.1.1 on 2024-10-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0004_parentcategory_category_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcategory',
            name='created_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='updated_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
