# Generated by Django 5.1.1 on 2024-11-22 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0005_product_category_name_temporaryproduct_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='outlet_name',
            new_name='outlet',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sub_category_name',
            new_name='sub_category',
        ),
        migrations.RenameField(
            model_name='temporaryproduct',
            old_name='brand_name',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='temporaryproduct',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='temporaryproduct',
            old_name='outlet_name',
            new_name='outlet',
        ),
        migrations.RenameField(
            model_name='temporaryproduct',
            old_name='sub_category_name',
            new_name='sub_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='used_for_inventory',
        ),
        migrations.RemoveField(
            model_name='temporaryproduct',
            name='used_for_inventory',
        ),
    ]
