# Generated by Django 5.1.1 on 2025-01-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0002_rename_shopowner_shop_alter_shop_table'),
        ('AppProduct', '0006_attributetype_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='att_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='attributetype',
            unique_together={('shop', 'att_type')},
        ),
    ]
