# Generated by Django 5.1.1 on 2024-10-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0006_alter_category_created_by_alter_category_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100, null=True)),
                ('product_outlet', models.CharField(max_length=100, null=True)),
                ('sku', models.CharField(max_length=100, null=True)),
                ('head_category', models.CharField(max_length=100, null=True)),
                ('season', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter')], default='Spring', max_length=6)),
                ('description', models.TextField(max_length=500, null=True)),
                ('brand_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.brand', to_field='name')),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.category', to_field='category_name')),
                ('pc_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.parentcategory', to_field='pc_name')),
                ('sub_category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.subcategory', to_field='sub_category_name')),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
    ]
