# Generated by Django 5.1.1 on 2024-10-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0007_alter_attribute_status_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand_name',
            new_name='name',
        ),
    ]
