# Generated by Django 5.1.1 on 2024-11-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0007_imagemodel_alter_temporaryproduct_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='attribute_name',
        ),
    ]
