# Generated by Django 5.1.1 on 2025-01-23 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0002_rename_shopowner_shop_alter_shop_table'),
        ('AppProduct', '0007_alter_attributetype_att_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AddField(
            model_name='variation',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
