# Generated by Django 5.1.1 on 2025-01-23 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0002_rename_shopowner_shop_alter_shop_table'),
        ('AppProduct', '0008_attribute_shop_variation_shop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AddField(
            model_name='headcategory',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppAdmin.shop'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='headcategory',
            name='hc_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='pc_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('shop', 'category_name')},
        ),
        migrations.AlterUniqueTogether(
            name='headcategory',
            unique_together={('shop', 'hc_name')},
        ),
        migrations.AlterUniqueTogether(
            name='parentcategory',
            unique_together={('shop', 'pc_name')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('shop', 'sub_category_name')},
        ),
    ]
