# Generated by Django 5.1.1 on 2024-11-26 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0009_subcatrgoryattribute_subcategory_attribute_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
