# Generated by Django 5.1.1 on 2024-10-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0011_product_category_name_product_pc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.brand', to_field='brand_name'),
        ),
    ]
