# Generated by Django 5.1.1 on 2024-12-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0011_rename_catrgoryattribute_categoryattribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryproduct',
            name='season',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
