# Generated by Django 5.1.1 on 2024-10-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0012_product_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='parentcategory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
