# Generated by Django 5.1.1 on 2024-10-15 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0014_product_created_at_product_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='vairation_name',
            new_name='variation_name',
        ),
    ]
