# Generated by Django 5.1.1 on 2024-10-15 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0016_remove_product_category_name_remove_product_pc_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_code', models.CharField(max_length=100, null=True, unique=True)),
                ('outlet_name', models.CharField(max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_outlet',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_outlet',
        ),
        migrations.AddField(
            model_name='product',
            name='outlet_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.outlet', to_field='outlet_name'),
        ),
    ]
