# Generated by Django 5.1.1 on 2024-10-17 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0017_outlet_remove_product_product_outlet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_type', models.CharField(max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_attribute_type',
            },
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='type',
        ),
        migrations.AddField(
            model_name='attribute',
            name='att_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.attributetype', to_field='att_type'),
        ),
    ]
