# Generated by Django 5.1.1 on 2024-10-17 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0018_attributetype_remove_attribute_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hc_name', models.CharField(max_length=100, null=True, unique=True)),
                ('symbol', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_head_category',
            },
        ),
        migrations.RemoveField(
            model_name='parentcategory',
            name='category_head',
        ),
        migrations.AddField(
            model_name='parentcategory',
            name='hc_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.headcategory', to_field='hc_name'),
        ),
    ]
