# Generated by Django 5.1.1 on 2024-10-17 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0019_headcategory_remove_parentcategory_category_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='attribute_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.attribute', to_field='attribute_name'),
        ),
    ]
