# Generated by Django 5.1.1 on 2024-10-18 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0021_alter_brand_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='head_category',
        ),
        migrations.AddField(
            model_name='product',
            name='hc_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.headcategory', to_field='hc_name'),
        ),
    ]
