# Generated by Django 5.1.1 on 2024-10-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0025_alter_product_color_alter_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='Product'),
        ),
    ]
