# Generated by Django 5.1.1 on 2024-10-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0027_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='outlet_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
