# Generated by Django 5.1.1 on 2024-10-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0029_alter_product_used_for_inventory_temporaryproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
