# Generated by Django 5.1.1 on 2024-11-15 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0030_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcategory',
            name='hc_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.headcategory'),
        ),
    ]
