# Generated by Django 5.1.1 on 2024-11-15 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0031_alter_parentcategory_hc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='attribute_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.attribute'),
        ),
        migrations.AlterField(
            model_name='category',
            name='pc_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.parentcategory'),
        ),
    ]
