# Generated by Django 5.1.1 on 2024-11-15 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0032_alter_category_attribute_name_alter_category_pc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='attribute_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.attribute'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.category'),
        ),
    ]
