# Generated by Django 5.1.1 on 2024-11-15 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0033_alter_subcategory_attribute_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='attribute_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.attribute'),
        ),
    ]
