# Generated by Django 5.1.1 on 2024-11-18 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0034_alter_variation_attribute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='att_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.attributetype'),
        ),
    ]
