# Generated by Django 5.1.1 on 2024-11-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0035_alter_attribute_att_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='att_type',
        ),
        migrations.AddField(
            model_name='attribute',
            name='att_type',
            field=models.ManyToManyField(to='AppProduct.attributetype'),
        ),
    ]
