# Generated by Django 5.1.1 on 2024-11-18 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0036_remove_attribute_att_type_attribute_att_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='att_type',
        ),
        migrations.AddField(
            model_name='attribute',
            name='att_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.attributetype'),
        ),
    ]
