# Generated by Django 5.1.1 on 2024-11-20 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0037_remove_attribute_att_type_attribute_att_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='attribute_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProduct.attributetype'),
        ),
    ]
