# Generated by Django 5.1.1 on 2024-11-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProduct', '0038_alter_category_attribute_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='attribute_name',
            new_name='attribute_type',
        ),
    ]
