# Generated by Django 5.1.1 on 2024-11-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('sku', models.CharField(max_length=200, null=True, unique=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('size', models.CharField(blank=True, max_length=100, null=True)),
                ('avail_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tbl_stock',
            },
        ),
    ]
