# Generated by Django 5.1.1 on 2024-10-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppStock', '0002_remove_stock_add_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='product_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='avail_quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
