# Generated by Django 5.1.1 on 2025-01-20 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopOwner',
            new_name='Shop',
        ),
        migrations.AlterModelTable(
            name='shop',
            table='tbl_shops',
        ),
    ]
